--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.2

-- Started on 2025-01-16 12:59:19 +07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3445 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 231 (class 1259 OID 16476)
-- Name: CartItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CartItems" (
    "CartItemId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "ShoppingCartId" integer NOT NULL,
    "ProductId" integer NOT NULL
);


ALTER TABLE public."CartItems" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16475)
-- Name: CartItem_CartItemId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CartItems" ALTER COLUMN "CartItemId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CartItem_CartItemId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16391)
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "CategoryId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "Description" character varying(256) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: Categories_CategoryID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "CategoryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_CategoryID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16416)
-- Name: OrderItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrderItems" (
    "OrderItemId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL
);


ALTER TABLE public."OrderItems" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16415)
-- Name: OrderItems_OrderItemID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrderItems" ALTER COLUMN "OrderItemId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItems_OrderItemID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16397)
-- Name: Orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Orders" (
    "OrderId" integer NOT NULL,
    "OrderDate" timestamp with time zone NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "Status" integer NOT NULL,
    "UserId" text NOT NULL,
    "Address" text DEFAULT ''::text NOT NULL,
    "Address2" text DEFAULT ''::text NOT NULL,
    "FirstName" text DEFAULT ''::text NOT NULL,
    "LastName" text DEFAULT ''::text NOT NULL,
    "Email" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Orders" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16396)
-- Name: Orders_OrderID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Orders" ALTER COLUMN "OrderId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_OrderID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16403)
-- Name: Products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Products" (
    "ProductId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(250) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "ImageUrl" character varying(250) NOT NULL,
    "CategoryId" integer NOT NULL,
    "IsDeleted" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."Products" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: Products_ProductID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Products" ALTER COLUMN "ProductId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_ProductID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16432)
-- Name: Reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reviews" (
    "ReviewId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text NOT NULL,
    "ProductId" integer NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."Reviews" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16431)
-- Name: Reviews_ReviewID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Reviews" ALTER COLUMN "ReviewId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reviews_ReviewID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16445)
-- Name: ShoppingCarts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ShoppingCarts" (
    "CartId" integer NOT NULL,
    "UserId" text NOT NULL
);


ALTER TABLE public."ShoppingCarts" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16444)
-- Name: ShoppingCarts_CartID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ShoppingCarts" ALTER COLUMN "CartId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShoppingCarts_CartID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16385)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3439 (class 0 OID 16476)
-- Dependencies: 231
-- Data for Name: CartItems; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3427 (class 0 OID 16391)
-- Dependencies: 219
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Categories" VALUES (1, 'Electronics', false, 'Electronic gadgets and accessories');
INSERT INTO public."Categories" VALUES (2, 'Books', false, 'Books for all ages');
INSERT INTO public."Categories" VALUES (3, 'Clothing', false, 'Clothing for all ages');
INSERT INTO public."Categories" VALUES (6, 'Clothing', true, 'Clothing for all ages');
INSERT INTO public."Categories" VALUES (5, 'Books', true, 'Books for all ages');
INSERT INTO public."Categories" VALUES (4, 'Electronics', true, 'Electronic gadgets and accessories');


--
-- TOC entry 3433 (class 0 OID 16416)
-- Dependencies: 225
-- Data for Name: OrderItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."OrderItems" VALUES (1, 2, 100.00, 1, 3);
INSERT INTO public."OrderItems" VALUES (2, 2, 500.00, 1, 2);


--
-- TOC entry 3429 (class 0 OID 16397)
-- Dependencies: 221
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Orders" VALUES (1, '2025-01-10 04:55:51.682477+00', 1200.00, 0, '0596b438-351c-426d-993b-5b5aa6fe97c2', 'Chung cư Prosper Plaza, 22/14 Phan Văn Hớn', '', 'Tuan', 'Cao', '');


--
-- TOC entry 3431 (class 0 OID 16403)
-- Dependencies: 223
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Products" VALUES (1, 'Macbook Pro M4', 'MacBook Pro 14 inch M4 16GB 512GB mang nguồn sức mạnh ấn tượng với con chip M4 10 lõi, GPU 10 lõi Neural Engine 16 lõi khai phá tiềm năng AI kinh ngạc, nâng cấp hiệu năng vượt trộ', 1000.00, 'https://cdn-images.vtv.vn/zoom/640_400/66349b6076cb4dee98746cf1/2024/10/18/macbook-pro-m4-06481241334562591351270-41727596355822000187891.webp', 1, false);
INSERT INTO public."Products" VALUES (2, 'Iphone 16 Pro Max', 'iPhone 16 Pro Max sở hữu màn hình 6.9 inch với công nghệ ProMotion, mang lại trải nghiệm hiển thị mượt mà và sắc nét, lý tưởng cho giải trí và làm việc', 500.00, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/i/p/iphone-16-pro-max.png', 1, false);
INSERT INTO public."Products" VALUES (3, 'Sony WH-CH520', 'Tai nghe Sony WH-CH520 sở hữu âm thanh kỹ thuật số DSEE giúp mang lại âm thanh chân thực cùng với đó là pin cho thời gian sử dụng tới 40 giờ', 100.00, 'https://sony.scene7.com/is/image/sonyglobalsolutions/wh-ch520_Primary_image?$categorypdpnav$&fmt=png-alpha', 1, false);
INSERT INTO public."Products" VALUES (4, 'Learn C# 13 and Net 9', 'An accessible guide for beginner-to-intermediate programmers to the concepts, real-world applications, and latest features of C# 13 and .NET 9, with hands-on exercises using Visual Studio and Visual Studio Code', 10.00, 'https://m.media-amazon.com/images/I/51TNLcQQrnL._AC_UF1000,1000_QL80_.jpg', 2, false);
INSERT INTO public."Products" VALUES (5, 'Tommy Hilfiger', 'TOMMY HILFIGER là thương hiệu thời trang hàng đầu thế giới, tôn vinh phong cách cổ điển kiểu Mỹ, đặc trưng với những thiết kế preppy phá cách.', 20.00, 'https://sithimy.s3.ap-southeast-1.amazonaws.com/sithimy/media/StPAN0QVdM1NLc2nV395fttIjh4dCFJQVI0JD5MS.jpg', 3, false);


--
-- TOC entry 3435 (class 0 OID 16432)
-- Dependencies: 227
-- Data for Name: Reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3437 (class 0 OID 16445)
-- Dependencies: 229
-- Data for Name: ShoppingCarts; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3425 (class 0 OID 16385)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20241126043546_Init', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241126084230_Order_Update_Status_Column_Type', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241128043748_Update_Entities_And_Relationship', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241128050818_Update_Column_Type_UserId', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241128051515_Remove_Quantity_Column_In_ShoppingCart', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241128083525_Add_IsDeleted_For_Product', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241203082702_Add_Description_For_Category', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241212045320_Add_Order_Detail_Properties', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241212051330_Add_Email_To_Order', '9.0.0');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20241212051415_Make_Email_Optional', '9.0.0');


--
-- TOC entry 3446 (class 0 OID 0)
-- Dependencies: 230
-- Name: CartItem_CartItemId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CartItem_CartItemId_seq"', 2, true);


--
-- TOC entry 3447 (class 0 OID 0)
-- Dependencies: 218
-- Name: Categories_CategoryID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_CategoryID_seq"', 6, true);


--
-- TOC entry 3448 (class 0 OID 0)
-- Dependencies: 224
-- Name: OrderItems_OrderItemID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OrderItems_OrderItemID_seq"', 2, true);


--
-- TOC entry 3449 (class 0 OID 0)
-- Dependencies: 220
-- Name: Orders_OrderID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Orders_OrderID_seq"', 1, true);


--
-- TOC entry 3450 (class 0 OID 0)
-- Dependencies: 222
-- Name: Products_ProductID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_ProductID_seq"', 10, true);


--
-- TOC entry 3451 (class 0 OID 0)
-- Dependencies: 226
-- Name: Reviews_ReviewID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Reviews_ReviewID_seq"', 1, false);


--
-- TOC entry 3452 (class 0 OID 0)
-- Dependencies: 228
-- Name: ShoppingCarts_CartID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ShoppingCarts_CartID_seq"', 1, true);


--
-- TOC entry 3273 (class 2606 OID 16537)
-- Name: CartItems PK_CartItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "PK_CartItems" PRIMARY KEY ("CartItemId");


--
-- TOC entry 3255 (class 2606 OID 16395)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId");


--
-- TOC entry 3264 (class 2606 OID 16420)
-- Name: OrderItems PK_OrderItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "PK_OrderItems" PRIMARY KEY ("OrderItemId");


--
-- TOC entry 3257 (class 2606 OID 16401)
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId");


--
-- TOC entry 3260 (class 2606 OID 16409)
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("ProductId");


--
-- TOC entry 3267 (class 2606 OID 16438)
-- Name: Reviews PK_Reviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId");


--
-- TOC entry 3269 (class 2606 OID 16449)
-- Name: ShoppingCarts PK_ShoppingCarts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ShoppingCarts"
    ADD CONSTRAINT "PK_ShoppingCarts" PRIMARY KEY ("CartId");


--
-- TOC entry 3253 (class 2606 OID 16389)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3270 (class 1259 OID 16491)
-- Name: IX_CartItems_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CartItems_ProductId" ON public."CartItems" USING btree ("ProductId");


--
-- TOC entry 3271 (class 1259 OID 16492)
-- Name: IX_CartItems_ShoppingCartId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CartItems_ShoppingCartId" ON public."CartItems" USING btree ("ShoppingCartId");


--
-- TOC entry 3261 (class 1259 OID 16455)
-- Name: IX_OrderItems_OrderId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderItems_OrderId" ON public."OrderItems" USING btree ("OrderId");


--
-- TOC entry 3262 (class 1259 OID 16456)
-- Name: IX_OrderItems_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrderItems_ProductId" ON public."OrderItems" USING btree ("ProductId");


--
-- TOC entry 3258 (class 1259 OID 16457)
-- Name: IX_Products_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Products_CategoryId" ON public."Products" USING btree ("CategoryId");


--
-- TOC entry 3265 (class 1259 OID 16458)
-- Name: IX_Reviews_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_ProductId" ON public."Reviews" USING btree ("ProductId");


--
-- TOC entry 3278 (class 2606 OID 16538)
-- Name: CartItems FK_CartItems_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("ProductId") ON DELETE CASCADE;


--
-- TOC entry 3279 (class 2606 OID 16543)
-- Name: CartItems FK_CartItems_ShoppingCarts_ShoppingCartId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "FK_CartItems_ShoppingCarts_ShoppingCartId" FOREIGN KEY ("ShoppingCartId") REFERENCES public."ShoppingCarts"("CartId") ON DELETE CASCADE;


--
-- TOC entry 3275 (class 2606 OID 16493)
-- Name: OrderItems FK_OrderItems_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("OrderId") ON DELETE CASCADE;


--
-- TOC entry 3276 (class 2606 OID 16498)
-- Name: OrderItems FK_OrderItems_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("ProductId") ON DELETE CASCADE;


--
-- TOC entry 3274 (class 2606 OID 16503)
-- Name: Products FK_Products_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("CategoryId") ON DELETE CASCADE;


--
-- TOC entry 3277 (class 2606 OID 16508)
-- Name: Reviews FK_Reviews_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("ProductId") ON DELETE CASCADE;


-- Completed on 2025-01-16 12:59:19 +07

--
-- PostgreSQL database dump complete
--

